version: '3.7'

services:
  db:
    container_name: ${POSTGRES_SERVER}
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    container_name: ${REDIS_HOST}
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../backend/:/backend
      - media_value:/backend/media
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  media_value:
  postgres_data:
  redis_data: