name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-isort mypy
        pip install -r backend/requirements.txt
    - name: Run flake8
      run: flake8 .
    - name: Run mypy
      run: mypy .

  build_docker:
    name: Docker image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Create env file'
        run: |
          cd infra
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env

      #- name: Build docker image
      #  run: docker-compose build

      - name: Build docker image backend-tests
        run: |
          cd infra
          docker-compose up backend-test
      - name: Pytest
        run: |
          cd infra
          docker-compose exec backend-test pytest

    